# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json


### modify_num_transactions_as_time_and_weekday(),
### generate_transactions(num_transactions, member_emails, room_types, guest_numbers)  함수 테스트
POST http://localhost:8000/test/generate_transactions
Accept: application/json


### Send to Kafka Test
POST http://localhost:8000/test/send_to_kafka
Accept: application/json
#Content-Type: application/json


### aggregate_with_spark
POST http://localhost:8000/test/aggregate_with_spark
Accept: application/json

### set_mysql_jdbc
POST http://localhost:8000/test/set_mysql_jdbc
Accept: application/json

//Content-Type: application/json

#
#  {
#    transaction data
#  }
